# Generated by Django 4.1.3 on 2023-09-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudstart', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
