# Generated by Django 4.1.3 on 2023-09-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudstart', '0004_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=16)),
                ('checkbox', models.BooleanField(default=False)),
            ],
        ),
    ]
